language: node_js
node_js:
  - "6"
  - "7"
  - "8"
addons:
  sonarcloud:
    organization: "iosr-ikm"
    token:
      secure: "IIUpyTyXaGdq83/+DIEvLJvgXYNFkC45qrsJutXKxt6bFcSyCoO7+0O/BxHbWQ15VdK+QDoevLrkpIeka1dtAww2QJT6O7HCVof6uS6PjNKFUlnoLRX0RqIW3TSI88pr3er+L0dOuO7lDTPrZ9UsWbPj1ewpkRhHuqUoy/8wq5VqA1g0hGkypqo6ulH3tKmGqHnqaEhEKmv6O/JlnLbRbE5wzSYgeLMsd5JN/jQpt+ptxbVXskfv7eodSCC2DOjADGOOR9E+bk526l26zlOsR8rkS/bqbkMezmK1tr3gdhfVCWDU0HtTNjJe9pNS1DAC/a7kBbtV2ewWdcnanmZ1k2vkB1aAc/z+48H03h0aB4ElZl5DonSvMf0B+S7LynrP4zmRhZo1dtdN9kzHmHe9IZOhrIp/8LsIodVul10Md0qUHXBw1sereqhp/eJGuuSs+LxMGP47ZQY0YmoOjc5CGxeObuIMlJ6KSj8a7fD2hrkok+T9SMaMx3Uz0kmfs9VNS9vuT94sLOZxDc/X6WttWr4CzvBnvq2QZwbBLi2+f73da7MR00jIFoupuht/SujTpkGORVvUKeH1UNBjm6BCwWsRrTxePJhLipG/axeg7aoamVF1yn0dCQ/fldLN++7PCnKiRKqjFaGz8/iHGsW2c6+zqzrUvz/34r9/IcBTwbA="
script:
  - npm test
  - sonar-scanner