language: node_js
node_js:
  - "6"
  - "7"
  - "8"
addons:
  sonarcloud:
    organization: "iosr-ikm"
    token:
      secure: "OAQ0TkLuEHRCG1VFONh44rvwQs3u8SVLJTGwChK8rq3IwubWO7hDvPq0PjRZLsJKwIdtM/eawLXn3ND0q/0hFG/RI1kv54UOUa5uML0WsZGTtO27IDPqD0BvUuzx+VpwpKtZjLlQ9Ao5t3XtiAeNUvZfIaW4EM6BdDi9Np28DAaurzop5K9vn6HgH0rnQM12cQr5KYECZtN1Kg0B26wjvtESk5FM3Xga47Vi8v2JNezGeKRWs99GWEJcRPyjxZCDumkw0nU4cmFCzV8d2BsNczA6+X8Ob+Nmr/4+9D4UcLAFYfwHD584Uy9OqXIPGlGCi5RKfVmYTLmAOnX714S3CfFeZHbtSn+fSuwaZ0ewy+9IN456J5E0Ti6QYbAVwXPW1eXE5GAA6Vane/vi9oYAJrQ7hT25wB95wCbo+BXLysL4XUJFqDWIBoMAUndxSJem0epOCwFQ38r41YQaa+ejf0X2sJlqxW4AEFvT4WK7dDkBP+5W9qAoGCQ/fM4pT8/2GniwEKSU95xUM2Z490elEf36kLx5pO5je2vFrSxPqIfZOs2yPdpvSY8ZWINfWHliHDA/G3AQNpgsov8dfSx4ZI4hirqXrdiAyKzG22WmiJ9lrM6IjhTmlZuOWnQ0RQJSHo2H+anFpJQfZD6AMQIkIW/MhDP1OBc9kBl9M7LD1U0="
script:
  - npm test
  - sonar-scanner